# Generated by Django 6.0.3 on 2026-04-18 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintabs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто просится')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='maintabs.budgetaccount', verbose_name='К какому счёту')),
            ],
        ),
    ]
