# Generated by Django 6.0.3 on 2026-04-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintabs', '0002_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Принят'), ('rejected', 'Отклонён'), ('expired', 'Участник присоединился к другому счёту')], default='pending', max_length=10),
        ),
    ]
