# Generated by Django 6.0.3 on 2026-04-21 12:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintabs', '0003_alter_joinrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название цели')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Всего нужно')),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Накоплено')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='maintabs.budgetaccount', verbose_name='Счёт бюджета')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MoneyContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], default='cash', max_length=10, verbose_name='Тип')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Баланс')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='maintabs.budgetaccount', verbose_name='Счёт бюджета')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_containers', to=settings.AUTH_USER_MODEL, verbose_name='Владелец контейнера')),
            ],
            options={
                'verbose_name': 'Контейнер денег',
                'verbose_name_plural': 'Контейнеры денег',
                'unique_together': {('account', 'name')},
            },
        ),
    ]
