# Generated by Django 6.0.3 on 2026-04-24 18:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintabs', '0006_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], default='expense', max_length=10, verbose_name='Тип')),
                ('is_goal_category', models.BooleanField(default=False, verbose_name='Категория "На цели"')),
                ('is_system', models.BooleanField(default=True, help_text='Предустановленная категория, недоступна для удаления.', verbose_name='Системная категория')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='maintabs.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важная трата')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='maintabs.budgetaccount', verbose_name='Семейный счёт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='maintabs.category', verbose_name='Категория')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='maintabs.moneycontainer', verbose_name='Счёт (контейнер)')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='maintabs.goal', verbose_name='Цель')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_as_subcategory', to='maintabs.category', verbose_name='Подкатегория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-datetime', '-id'],
            },
        ),
    ]
