# Generated by Django 6.0.3 on 2026-04-28 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintabs', '0007_category_operation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moneycontainer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='moneycontainer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddConstraint(
            model_name='moneycontainer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('account', 'name'), name='uniq_active_container_name'),
        ),
    ]
