# Generated by Django 6.0.3 on 2026-05-07 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintabs', '0008_alter_moneycontainer_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Хранится как первое число месяца', verbose_name='Месяц')),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Лимит')),
                ('importance', models.BooleanField(blank=True, null=True, verbose_name='Важность (NULL=не задана)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_plans', to='maintabs.budgetaccount', verbose_name='Семейный счёт')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spending_plans_as_category', to='maintabs.category', verbose_name='Категория')),
                ('scope_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spending_plans_scope', to=settings.AUTH_USER_MODEL, verbose_name='Чьи счета учитывать (NULL = все)')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spending_plans_as_subcategory', to='maintabs.category', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'План расходов',
                'verbose_name_plural': 'Планы расходов',
                'constraints': [models.UniqueConstraint(fields=('account', 'month', 'scope_user', 'importance', 'category', 'subcategory'), name='uniq_spending_plan_key')],
            },
        ),
    ]
