# Generated by Django 6.0.3 on 2026-05-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintabs', '0009_spendingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='is_read_by_owner',
            field=models.BooleanField(default=False, verbose_name='Прочитано владельцем'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
